### 경로 내 휴게소 검색 API
GET http://localhost:8082/api/highways/reststops?
    from=37.3171,127.0866&
    to=34.9564,127.58748&
    roadNames=경부선,호남선,순천완주선

### 휴게소 상세 정보 조회 API
GET http://localhost:8082/api/reststop/info?reststopCode=000013

