services:
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: 8potatoes-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: 'master'
      MYSQL_DATABASE: reststop
      MYSQL_USER: 'master'
      MYSQL_PASSWORD: 'master'
      TZ: 'Asia/Seoul'
    ports:
      - "3307:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf

  batch-application:
    container_name: eightpotatoes-batch-application
    image: jun108059/eightpotatoes-batch-application:main
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reststop?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: master
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      PORT: 8081
      MODULE: batch
    ports:
      - "8081:8081"
    depends_on:
      - db

  external-api-application:
    container_name: eightpotatoes-external-api-application
    image: jun108059/eightpotatoes-external-api-application:main
    build:
      context: ../
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Seoul
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/reststop?serverTimezone=Asia/Seoul
      SPRING_DATASOURCE_USERNAME: master
      SPRING_DATASOURCE_PASSWORD: master
      SPRING_DATASOURCE_DRIVER: com.mysql.cj.jdbc.Driver
      PORT: 8082
      MODULE: external-api
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  mysql_data: # MySQL 데이터 저장소