spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/eightpotatoes_db
    username: ${{secrets.dbUserName}}"
    password: ${{secrets.dbPassword}}"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
