spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}
  mvc:
    async:
      request-timeout: 1200000 # 20 minutes
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
api:
  base:
    url: http://data.ex.co.kr
  key: 3951846914