server:
  port: 8099
spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3307/reststop?serverTimezone=Asia/Seoul
    username: master
    password: master
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
api:
  base:
    url: https://data.ex.co.kr
  key: 3951846914