name: Build and Deploy to NCP

on:
  push:
    branches:
      - main
      - ci-cd-test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name:  Check out the repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradlew build
        run: ./gradlew clean build -x test

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_REF##*/}" | sed 's/\//-/g' >> $GITHUB_ENV

      - name: Build and Push Batch Application Image
        env:
          IMAGE_NAME: eightpotatoes-batch-application
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG} -f ./Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}}

      - name: Build and Push External API Application Image
        env:
          IMAGE_NAME: eightpotatoes-external-api-application
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG} -f ./Dockerfile .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${IMAGE_NAME}:${IMAGE_TAG}}

      - name: Deploy to NCP server with SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NCP_HOST }}
          username: ${{ secrets.NCP_USERNAME }}
          password: ${{ secrets.NCP_PASSWORD }}
          port: ${{ secrets.NCP_PORT }}
          script: |
            cd /docker/docker-compose
            docker-compose pull
            docker-compose down || true
            docker-compose up -d